#!/usr/bin/env php
<?php
require __DIR__ . '/vendor/autoload.php';

use Sarfraznawaz2005\Floyer\Commands\Deploy;
use Sarfraznawaz2005\Floyer\Connectors\FTP;
use Sarfraznawaz2005\Floyer\Drivers\Git;
use Symfony\Component\Console\Application;

$application = new Application();

$application->add(new Deploy(new Git(), new FTP()));

$application->run();